spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service360
    username: postgres
    password: Service@360
    driver-class-name: org.postgresql.Driver

  jpa:
#    hibernate:
#      ddl-auto: create-drop
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect





