server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service360
    username: postgres
    password: Service@360
    driver-class-name: org.postgresql.Driver

  jpa:
    #    hibernate:
    #      ddl-auto: create-drop
#    hibernate:
#      ddl-auto
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: service.360.50@gmail.com
#    password: jgarjwrndtbgwxna
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000








